
#-------------
# Alt-Tab Fix
#-------------

[AltTabFix]
# The main feature, fixes stuck inputs when alt tabbing.
bEnable = True
# Determines the duration in game frames in which all input passed to the game is discarded and blocked.
iFramesToBlock = 2

#-----------------------
# Experimental features.
#-----------------------

[FocusTheft]
# Enable/disable patches related to the game window creation process.
# This patch modifies the game's window creation process to not aquire focus when the game window is created.
# The idea behind this patch comes from a personal annoyance where while waiting for the game to load to the main menu it would steal focus while doing other things.
bEnable = False

[Misc]
# Skyrim normally eats any windows shortcuts even with mods like the media keys fix.
# This patch allows the use of the snipping tool by intercepting the Win+Shift+S key combination and manually launching it.
bEnableSnippingToolForward = False
